#ifndef CONFIG_H_
#define CONFIG_H_

//SERIAL SETTINGS
#define BAUD 115200

//ROBOT ARM LENGTH 
#define SHANK_LENGTH 120.0
#define END_EFFECTOR_OFFSET 50.0 // LENGTH FROM UPPER SHANK BEARING TO MIDPOINT OF END EFFECTOR IN MM

//INITIAL INTERPOLATION SETTINGS 
//  INITIAL_XYZ should form vertical lower arm & horizontal upper arm in 90 degrees
#define INITIAL_X 0.0 // CARTESIAN COORDINATE X 
#define INITIAL_Y 170.0 // CARTESIAN COORDINATE Y ((MUST INCLUDE END_EFFECTOR_OFFSET))
#define INITIAL_Z 120.0 // CARTESIAN COORDINATE Z
//  CALIBRATE HOME STEPS TO REACH DESIRED INITIAL_XYZ POSITIONS
#define X_HOME_STEPS 700 //860 // STEPS FROM X_ENDSTOP TO INITIAL_XYZ FOR UPPER ARM
#define Y_HOME_STEPS 1790 //1940 // STEPS FROM Y_ENDSTOP TO INITIAL_XYZ FOR LOWER ARM
#define Z_HOME_STEPS 3650 // STEPS FROM Z_ENDSTOP TO INITIAL_XYZ FOR ROTATION CENTER

//HOMING SETTINGS: 
#define HOME_X_STEPPER true // "true" IF ENDSTOP IS INSTALLED
#define HOME_Y_STEPPER true // "true" IF ENDSTOP IS INSTALLED
#define HOME_Z_STEPPER true // "true" IF ENDSTOP IS INSTALLED
#define HOME_ON_BOOT false // "true" IF HOMING REQUIRED AFTER POWER ON
#define HOME_DWELL 1000 // INCREASE TO SLOW DOWN HOMING SPEED

//STEPPER SETTINGS:
#define MICROSTEPS 16 // MICROSTEPPING CONFIGURATION ON RAMPS1.4
#define STEPS_PER_REV 200 // NEMA17 STEPS PER REVOLUTION
#define INVERSE_X_STEPPER false // CHANGE IF STEPPER MOVES OTHER WAY
#define INVERSE_Y_STEPPER true // CHANGE IF STEPPER MOVES OTHER WAY
#define INVERSE_Z_STEPPER false // CHANGE IF STEPPER MOVES OTHER WAY

//ENDSTOP SETTINGS:
#define X_MIN_INPUT 1 // OUTPUT VALUE WHEN SWITCH ACTIVATED
#define Y_MIN_INPUT 1 // OUTPUT VALUE WHEN SWITCH ACTIVATED
#define Z_MIN_INPUT 1 // OUTPUT VALUE WHEN SWITCH ACTIVATED

//GEAR RATIO SETTINGS
#define MOTOR_GEAR_TEETH 20.0 // 20.0 FOR 20SFFACTORY BELT VERSION   9.0 FOR FTOBLER GEAR VERSION
#define MAIN_GEAR_TEETH 90.0 // 90.0 FOR 20SFFACTORY BELT VERSION   32.0 FOR FTOBLER GEAR VERSION

//EQUIPMENT SETTINGS
#define LASER true // 12V LASER CONNECTED TO LASER_PIN
#define PUMP false // 12V AIR PUMP CONNECTED TO PUMP_PIN
#define FAN_DELAY 120 // FAN ON IN SECONDS

//28BYJ GRIPPER SETTINGS
#define GRIP_STEPS 1200 //FTOBLER: 1200

//COMMAND QUEUE SETTINGS
#define QUEUE_SIZE 255

//PRINT REPLY SETTING
#define PRINT_REPLY true // "true" TO PRINT MSG AFTER ONE COMMAND IS PROCESSED
#define PRINT_REPLY_MSG "ok" // MSG SENT FOR USER'S POST PROCESSING WITH OTHER SOFTWARE

#endif
